# Generated by Django 3.0.6 on 2020-06-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default=0, max_length=128, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
    ]
