# Generated by Django 3.0.6 on 2020-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_main',
            field=models.BooleanField(default=False, verbose_name='Размещать на главной странице'),
        ),
    ]
