# Generated by Django 3.0.6 on 2020-06-13 11:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200611_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-article'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Project\\simple-shop\\static'), upload_to=''),
        ),
    ]
