# Generated by Django 3.0.6 on 2020-06-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200606_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='C:\\Project\\simple-shop\\resources\\static'),
        ),
    ]
