# Generated by Django 3.0.6 on 2020-06-13 12:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200613_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Project\\simple-shop\\media'), upload_to='images'),
        ),
    ]
