# Generated by Django 3.0.6 on 2020-06-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200615_2048'),
        ('shop', '0008_auto_20200614_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(related_name='buyers', through='cart.Cart', to='cart.Order'),
        ),
    ]
