# Generated by Django 3.0.6 on 2020-06-18 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_clothes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='for_main',
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('for_main', models.BooleanField(default=False, verbose_name='Размещать на главной странице')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='shop.Category')),
            ],
            options={
                'verbose_name': 'Гаджет',
                'verbose_name_plural': 'Смартфоны и аксессуары',
                'ordering': ['-article'],
            },
            bases=('shop.product',),
        ),
    ]
