# Generated by Django 3.0.6 on 2020-06-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200617_2123'),
        ('shop', '0011_auto_20200618_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users',
        ),
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(related_name='goods', through='cart.Cart', to='cart.Order'),
        ),
    ]
