# Generated by Django 2.2.10 on 2020-06-21 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200618_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя пользователя')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('estimation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('session_id', models.CharField(max_length=128, verbose_name='Ключ сессии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.Product')),
            ],
        ),
    ]
