# Generated by Django 2.2.10 on 2020-06-21 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_сomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сomment',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы о товарах'},
        ),
    ]
