# Generated by Django 2.2.10 on 2020-06-24 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200624_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа товарных категорий', 'verbose_name_plural': 'Пункты меню сайта'},
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.Group', verbose_name='Состоит в группе'),
        ),
    ]
