# Generated by Django 3.0.6 on 2020-06-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='pay_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='session_id',
        ),
    ]
